
package com.lovo.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MessageService", targetNamespace = "http://service.ws.lovo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MessageService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pushMessage", targetNamespace = "http://service.ws.lovo.com/", className = "com.lovo.ws.client.PushMessage")
    @ResponseWrapper(localName = "pushMessageResponse", targetNamespace = "http://service.ws.lovo.com/", className = "com.lovo.ws.client.PushMessageResponse")
    @Action(input = "http://service.ws.lovo.com/MessageService/pushMessageRequest", output = "http://service.ws.lovo.com/MessageService/pushMessageResponse")
    public String pushMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
