
package com.lovo.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessageServiceService", targetNamespace = "http://service.ws.lovo.com/", wsdlLocation = "http://192.168.10.222:8000/message?wsdl")
public class MessageServiceService
    extends Service
{

    private final static URL MESSAGESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSAGESERVICESERVICE_EXCEPTION;
    private final static QName MESSAGESERVICESERVICE_QNAME = new QName("http://service.ws.lovo.com/", "MessageServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.222:8000/message?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSAGESERVICESERVICE_WSDL_LOCATION = url;
        MESSAGESERVICESERVICE_EXCEPTION = e;
    }

    public MessageServiceService() {
        super(__getWsdlLocation(), MESSAGESERVICESERVICE_QNAME);
    }

    public MessageServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSAGESERVICESERVICE_QNAME, features);
    }

    public MessageServiceService(URL wsdlLocation) {
        super(wsdlLocation, MESSAGESERVICESERVICE_QNAME);
    }

    public MessageServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSAGESERVICESERVICE_QNAME, features);
    }

    public MessageServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MessageService
     */
    @WebEndpoint(name = "MessageServicePort")
    public MessageService getMessageServicePort() {
        return super.getPort(new QName("http://service.ws.lovo.com/", "MessageServicePort"), MessageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageService
     */
    @WebEndpoint(name = "MessageServicePort")
    public MessageService getMessageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.lovo.com/", "MessageServicePort"), MessageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSAGESERVICESERVICE_EXCEPTION!= null) {
            throw MESSAGESERVICESERVICE_EXCEPTION;
        }
        return MESSAGESERVICESERVICE_WSDL_LOCATION;
    }

}
