mybatis-plus:
  #MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:mapper/*.xml
  #  MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，
  #注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  typeAliasesPackage: com.lovo.lcntwo.bean


  configuration:
    #使用驼峰法映射属性,配置这个resultType可以映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 配置表明前缀，例如表设计时表名为tb_manager，对应entity为Manager
      # table-prefix: tb_
      #逻辑已删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0
      # 是否开启like查询，即对 stirng 字段是否使用 like，默认不开启
      # column-like: false

logging:
  level:
    # 日志级别，显示操作sql
     com.lovo.lcntwo.mapper: info
server:
  port: 6667
spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/j174?useUnicode=true&characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    registerWithEureka: false  #是否向服务器注册
    fetchRegistry: false
